services:
  node1:
    image: centos:latest
    container_name: centos_node1
    tty: true
    stdin_open: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /share
    command: /bin/bash -c "tail -f /dev/null"

  node2:
    image: centos:latest
    container_name: centos_node2
    tty: true
    stdin_open: true
    command: /bin/bash -c "tail -f /dev/null"
