- name: 'ansible vault test'
  hosts: all
  vars_files:
    - password.txt

  tasks:
    - name: copy source dir to destination dir
      copy:
        src: ./inventory.ini
        dest: /tmp/inventory.txt

    - name: copy source dir to destination dir#2
      copy:
        src: ./inventory.ini
        dest: /tmp/inventory2.txt

    - name: Create password file
      ansible.builtin.lineinfile:
        path: /tmp/test.txt
        line: "password={{ password }}"
        create: true
        mode: '0600'

    - name: delete password.txt
      ansible.builtin.file:
        path: /tmp/inventory.txt
        state: absent
