pipeline {
    agent any
    tools { nodejs "nodejs"}
    
    stages {
        
        stage('slack start') {
            steps {
             slackSend (color: "#439FE0", message: "Build Started!!! : ${env.JOB_NAME} ${env.BUILD_NUMBER}")
            
            }
        }
        
        stage('Workspace Clean') {
            steps {
              cleanWs()
            }
        }
        stage('git clone') {
            steps {
                sh """
                   git clone 'https://github.com/leesanghoon94/myApp.git'
                   """
            }
        }
        
        stage('deploy') {
            steps {
                sh  """
                    cd myApp/server/ansible
                    ansible-playbook -i inventory playbook.yaml
                    """
            }
        }
        
        stage('end'){
            steps {
                slackSend(message:"end")
            }
        }
    }
}
