FROM centos:8

# CentOS Stream 8으로 전환
RUN dnf install -y centos-release-stream && \
    dnf swap -y centos-linux-repos centos-stream-repos && \
    dnf distro-sync -y

# NFS와 관련된 패키지 설치
#RUN yum install -y nfs-utils rpcbind

# systemd 관련 설정
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ "$i" == "systemd-tmpfiles-setup.service" ] || rm -f $i; done) && \
    rm -f /lib/systemd/system/multi-user.target.wants/* && \
    rm -f /etc/systemd/system/*.wants/* && \
    rm -f /lib/systemd/system/local-fs.target.wants/* && \
    rm -f /lib/systemd/system/sockets.target.wants/*udev* && \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl* && \
    rm -f /lib/systemd/system/basic.target.wants/* && \
    rm -f /lib/systemd/system/anaconda.target.wants/*

VOLUME [ "/sys/fs/cgroup" ]

# 필요한 디렉토리 생성
RUN mkdir -p /srv/nfs

# NFS 설정 파일 복사
COPY exports /etc/exports

# 포트 오픈
EXPOSE 111/udp 2049/tcp 20048/tcp 20048/udp

# NFS와 관련된 서비스 실행 스크립트 복사 및 실행
COPY start.sh /start.sh
RUN chmod +x /start.sh

STOPSIGNAL SIGRTMIN+3

CMD ["/usr/sbin/init"]

