FROM ubuntu:16.04
LABEL maintainer="alice <example@hi.com>"
RUN apt-get update
RUN apt-get install apache2 -y
COPY index.html /var/www/html
WORKDIR /var/www/html
RUN ["/bin/bash", "-c", "echo FASTCAMPUS >> index2.html"]
EXPOSE 80
CMD apachectl -DFOREGROUND
