- name: Mysql example
  hosts: ubuntu1
  become: yes

  pre_tasks:

    - name: Create virtual environment
      command: python3 -m venv /opt/myenv

    - name: Install pymysql inside venv
      command: /opt/myenv/bin/pip3 install pymysql cryptography

#    - name: Set Python interpreter to venv
#      lineinfile:
#        path: /etc/environment
#        line: 'ansible_python_interpreter=/opt/myenv/bin/python'

#      - name: Install pymysql
#      ansible.builtin.pip:
#        name: pymysql
#        state: present

  tasks:
    - name: Create user
      community.mysql.mysql_user:
        login_host: 192.168.1.2
        login_user: root
        login_password: password1234
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present
