{{- if .Values.apps.front.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  selector:
    app: front
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: {{ .Values.apps.front.image.repository }}:{{ .Values.apps.front.image.tag | default "latest" }} #leesanghoon94/front-local:v0.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
        {{- toYaml .Values.apps.front.resources | nindent 12}}
{{- end }}