{{- if .Values.ingress.subnets }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}

    # alb.ingress.kubernetes.io/transforms.${transforms-name}: [
    #   {
    #     "type": "url-rewrite",
    #     "urlRewriteConfig": {
    #       "rewrites": [
    #         {
    #           "regex": "^\\/api\\/().+)$",
    #           "replace": "$"
    #         }
    #       ]
    #     }
    #   }
    # ]
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: server
                port:
                  number: 3333

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: myapp
#   annotations:
#     alb.ingress.kubernetes.io/load-balancer-name: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

# spec:
#   ingressClassName: alb

#   rules:
#     - http:
#         paths:
#           # frontend
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: frontend
#                 port:
#                   number: 80

#           # backend api
#           - path: /api
#             pathType: Prefix
#             backend:
#               service:
#                 name: server
#                 port:
#                   number: 3333


{{- end }}
