version: '3.9'

services:
  ubuntu1:
    image: ubuntu:latest
    container_name: ubuntu1
    privileged: true
    entrypoint: ["/bin/bash" ,"-c", "apt-get update && apt-get install openssh-server vim -y && tail -f /dev/null"]
    ports:
      - "2221:22"

  ubuntu2:
    image: ubuntu:latest
    container_name: ubuntu2
    privileged: true
    entrypoint: ["/bin/bash" ,"-c", "apt-get update && apt-get install openssh-server -y && tail -f /dev/null"]
    ports:
      - "2222:22"
