# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Docker로 실행할 기본 머신 설정
  config.vm.define "ubuntu" do |d|
    d.vm.provider "docker" do |docker_config|
      docker_config.image = "ubuntu"
      docker_config.cmd = ["tail", "-f", "/dev/null"] # 컨테이너가 계속 실행되도록 명령어 추가
      docker_config.network :public_network, type: "dhcp", bridge: ["eth0"]
    end
  end

  # 1부터 3까지의 노드를 정의
  (1..2).each do |i|
    config.vm.define "ubuntu#{i}" do |subconfig|
      subconfig.vm.provider "docker" do |docker_config|
        docker_config.image = "ubuntu" # 동일한 이미지를 사용
        docker_config.cmd = ["tail", "-f", "/dev/null"]
        docker_config.provision "shell", inline: <<-SHELL
          apt update
          apt install net-tools vim ssh-server -y
        SHELL
      end
      subconfig.vm.hostname = "ubuntu#{i}" # 각 머신에 고유한 호스트 이름 설정
    end
  end

end
