apps:
  front:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 100
      averageUtilization: 80
      targetMemoryUtilizationPercentage: 70
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    image:
      repository: leesanghoon94/front-eks
      # Overrides the image tag whose default is the latest.
      tag: "c696f"
  server:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 100
      averageUtilization: 75
      targetMemoryUtilizationPercentage: 80
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    image:
      repository: leesanghoon94/server-eks
      # Overrides the image tag whose default is the latest.
      tag: "c696f"
mysql: true
ingress:
  subnets: subnet-012efc65ee06d256b, subnet-0e7852073febed00f
