apps:
  front:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      averageUtilization: 80
      targetMemoryUtilizationPercentage: 70
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    image:
      repository: leesanghoon94/front-eks
      # Overrides the image tag whose default is the latest.
      tag: "628c7"
  server:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      averageUtilization: 75
      targetMemoryUtilizationPercentage: 80
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    image:
      repository: leesanghoon94/server-eks
      # Overrides the image tag whose default is the latest.
      tag: "628c7"
mysql: true
ingress:
  subnets: subnet-0add9a61b431a9ed4, subnet-08ceb20659e0c6579
