- name: example
  hosts: all
  tasks:
    - name: echo linux distribution
      ansible.builtin.debug:
          var: ansible_facts.distribution

    - name: echo host ip
      ansible.builtin.debug:
        msg: "host ip: {{ ansible_facts.env.SSH_CONNECTION.split('')[2] }}"
        when: ansible_cats.distribution == 'ubuntu'