- name: Example
  hosts: all


  tasks:
    - name: Install curl (non-idempotent)
      ansible.builtin.command: apt install -y curl

    - name: Ensure curl is installed
      ansible.builtin.apt:
        name: curl
        state: present
