# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check out repository code
              uses: actions/checkout@v6
      
      - name: Get image tag(version)
<<<<<<< HEAD
          id: image
          run: |
            VERSION=$(echo ${{ github.sha }} | cut -c1-5)
            echo VERSION=$VERSION
            echo "::set-output name=version::$VERSION"
            
=======
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-5)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      
>>>>>>> ffa7cc4 (build.yml 수정)
      - name: build,tag,and push image to docker hub
        id: image-info
        env:
          IMAGE_TAG: ${{ steps.image.outputs.version }}
          DOCKERID: leesanghoon94
        working-directory: front
        run: |
          npm install
          npm run build
          echo "::set-output name=image_tag::$IMAGE_TAG"
          docker build -t leesanghoon94/front-eks:$IMAGE_TAG . 
          docker push leesanghoon94/front-eks:$IMAGE_TAG

      - name: build,tag,and push image to docker hub
        id: image-info
        env:
          IMAGE_TAG: ${{ steps.image.outputs.version }}
          DOCKERID: leesanghoon94
        working-directory: server
        run: |
          npm install
          echo "::set-output name=image_tag::$IMAGE_TAG"
          docker build -t leesanghoon94/server-eks:$IMAGE_TAG . 
          docker push leesanghoon94/server-eks:$IMAGE_TAG

    outputs:
      image_tag: ${{ steps.image.outputs.version }}
      sha: ${{ github.sha }}
  
  deploy:
    needs: build
    name: apply docker image tag to frontend deployment manifest
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
      GIT_ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
      HASH: ${{ needs.build.outputs.sha }}
      GIT_REPO: leesanghoon94/myApp

    steps:
      - name: Clone Deploy repository
        uses: actions/checkout@v2
        with:
          repository: ${{ env.GIT_REPO }}
          ref: "main"
          token: ${{ env.GIT_ACCESS_TOKEN }}

      - name: Image Tag Change
        uses: mikefarah/yq@v4.9.6
        with:
          cmd: yq e --inplace '.image.tag = "${{ env.IMAGE_TAG }}"' myapp/values.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          cmd: |
            helm lint .
            helm package .
            helm index . https://leesanghoon94/myApp

          token: ${{ env.GIT_ACCESS_TOKEN }}
          commit-message: "deploy: myapp-${{ env.HASH }}"
          base: main
          branch: gh-pages-${{ env.HASH }}
          title: "deploy: myapp-${{ env.HASH }}"

          labels: |
            automerge
