# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get image tag(version)
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-5)
          echo VERSION=$VERSION
          echo "front_version=$VERSION" >> "FRONT_TAG"
          echo "server_version=$VERSION" >> "SERVER_TAG"

      - name: build,tag,and push image to docker hub
        id: front_image
        env:
          FRONT_IMAGE: ${{ steps.image.outputs.front_version }}
          DOCKERID: leesanghoon94
        working-directory: front
        run: |
          npm install
          npm run build
          echo "image build and push~~~~~"
          docker build -t $DOCKERID/front-eks:$FRONT_IMAGE . 
          docker push $DOCKERID/front-eks:$FRONT_IMAGE

      - name: build,tag,and push image to docker hub
        id: server_image
        env:
          SERVER_IMAGE: ${{ steps.image.outputs.server_version }}
          DOCKERID: leesanghoon94
        working-directory: server
        run: |
          npm install
          # echo "::set-output name=image_tag::$SERVER_IMAGE"
          docker build -t $DOCKERID/server-eks:$SERVER_IMAGE . 
          docker push $DOCKERID/server-eks:$SERVER_IMAGE

    outputs:
      front_image: ${{ steps.front_image.outputs.image_tag }}
      server_image: ${{ steps.server_image.outputs.image_tag }}
      sha: ${{ github.sha }}

  deploy:
    needs: build
    name: apply docker image tag to frontend deployment manifest
    runs-on: ubuntu-latest
    env:
      FRONT_IMAGE: ${{ needs.build.outputs.front_image }}
      SERVER_IMAGE: ${{ needs.build.outputs.server_image }}
      GIT_ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
      HASH: ${{ needs.build.outputs.sha }}
      GIT_REPO: leesanghoon94/myApp

    steps:
      - name: Clone Deploy repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GIT_REPO }}
          ref: "main"
          token: ${{ env.GIT_ACCESS_TOKEN }}

      - name: Image Tag Change
        uses: mikefarah/yq@v4.9.6
        with:
          cmd: |
            echo ${env.FRONT_IMAGE}
            yq e --inplace '.apps.front.image.tag = "${{ env.FRONT_IMAGE }}"' myapp/values.yaml 
            yq e --inplace '.apps.server.image.tag = "${{ env.SERVER_IMAGE }}"' myapp/values.yaml

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          # cmd: |
          #   helm lint .
          #   helm package .
          #   helm index . https://leesanghoon94/myApp

          token: ${{ env.GIT_ACCESS_TOKEN }}
          commit-message: "deploy: myapp-${{ env.HASH }}"
          base: main
          branch: gh-pages-${{ env.HASH }}
          title: "deploy: myapp-${{ env.HASH }}"

          labels: |
            automerge
