# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 이미지 태그
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-5)
          echo VERSION=$VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: build,tag,and push image to docker hub
        id: front_image
        env:
          TAG: ${{ steps.image.outputs.version }}
          DOCKERID: leesanghoon94
        working-directory: front
        run: |
          npm install
          npm run build
          echo "image build and push~~~~~"
          docker build -t $DOCKERID/front-eks:$TAG . 
          docker push $DOCKERID/front-eks:$TAG

      - name: build,tag,and push image to docker hub
        id: server_image
        env:
          TAG: ${{ steps.image.outputs.version }}
          DOCKERID: leesanghoon94
        working-directory: server
        run: |
          npm install
          # echo "::set-output name=image_tag::$TAG"
          docker build -t $DOCKERID/server-eks:$TAG . 
          docker push $DOCKERID/server-eks:$TAG

    outputs:
      image_tag: ${{ steps.image.outputs.version }}
      sha: ${{ github.sha }}

  deploy:
    needs: build
    name: replace manifest image tag
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.build.outputs.image_tag }}
      GIT_ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
      HASH: ${{ needs.build.outputs.sha }}
      GIT_REPO: leesanghoon94/myApp

    steps:
      - name: Clone Deploy repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GIT_REPO }}
          ref: "main"
          token: ${{ env.GIT_ACCESS_TOKEN }}

      - name: Image Tag Change
        uses: mikefarah/yq@master
        with:
          cmd: |
            echo $TAG
            echo ${{ needs.build.outputs.image_tag }}
            echo ${{ steps.image.outputs.version }}
            yq e --inplace '.apps.front.image.tag = ${{ needs.build.outputs.image_tag }}' myapp/values.yaml 
            yq e --inplace '.apps.server.image.tag = "${{ steps.image.outputs.version }}"' myapp/values.yaml

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v8.1.1
      #   with:
      #     # cmd: |
      #     #   helm lint .
      #     #   helm package .
      #     #   helm index . https://leesanghoon94/myApp

      #     token: ${{ env.GIT_ACCESS_TOKEN }}
      #     commit-message: "deploy: myapp-${{ env.HASH }}"
      #     base: main
      #     branch: gh-pages-${{ env.HASH }}
      #     title: "deploy: myapp-${{ env.HASH }}"

      #     labels: |
      #       automerge
