name: fuck

run-name: ${{ github.actor }} is testing out GitHub Actions

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "브랜치이름: ${{ github.ref }} 레포이름: ${{ github.repository }} 깃헙객체: ${{ github }}"

      - name: Check out repository code
        uses: actions/checkout@v6
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: Get image tag(version)
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-5)
          echo VERSION=$VERSION
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

      - name: 변수 출력해봄 궁금
        id: image-info
        env:
          IMAGE_TAG: $GITHUB_OUTPUT
          DOCKERID: leesanghoon94
          STEP_OBJ: ${{ steps }}
        run: |
          echo $STEP_OBJ
          echo $IMAGE_TAG

    outputs:
      image_tag: ${{ steps.image.outputs.version }}
      sha: ${{ github.sha }}
