- name: test
  hosts: localhost

  tasks:
    - name: check
      ansible.builtin.command:
        uptime
      register: uptime_result

    - name: debug
      ansible.builtin.debug:
        msg: "output: {{ uptime_result.stdout }}"

    - name: curl
      ansible.builtin.command:
        curl -I https://google.com
      register: result
      retries: 5
      delay: 10
      until: result.rc == 0

    - name: failed_when
      ansible.builtin.command: cat /var/log/app.log
      register: result
      failed_when: result.rc ==0